services:
  - type: web
    name: mushroom-backend
    env: python
    rootDir: backend
    buildCommand: python -m pip install --upgrade pip && python -m pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: FLASK_DEBUG
        value: false

  - type: web
    name: mushroom-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install ; npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
